### ISSUE TITLE
Portability to R 4.0

### ISSUE THREAD

**Issue by caravagn** [caravagnalab/mobster#16]
Require the new R version due in April 2020.

**Comment by caravagn** [comment]
With no rush, we will have to check it works with a fresh install.

**Comment by marcjwilliams1** [comment]
I get this error on R v4.0 FYI
```
Error: Failed to install 'mobster' from GitHub:
  (converted from warning) package ‘vcfR’ is not available (for R version 4.0.2)
```

Looks like vcfR will reappear on CRAN at some point (https://github.com/knausb/vcfR/issues/165)

**Comment by luca-dex** [comment]
Hi @marcjwilliams1 ,
there's not much we can do to make the package available on CRAN however you can install vcfR directly from their github repositoriy ( https://github.com/knausb/vcfR ) with the command:

```
devtools::install_github(repo="knausb/vcfR")
library(vcfR)
```

**Comment by marcjwilliams1** [comment]
Yes, was just flagging in case this hadn't been spotted. vcfR doesn't look key so it could be moved to suggests and/or added to remotes if we want a clean install.

**Comment by caravagn** [comment]
Thanks @marcjwilliams1 it makes sense. There is a number of packages that have really minor importance for mobster to work. This is one of those as it only help some pre-processing of VCF files. I wish there was (or I knew) some elegant way of declaring some packages are required, and others as optional in terms of dependencies...

**Comment by luca-dex** [comment]
@caravagn give me 5 minutes... http://r-pkgs.had.co.nz/description.html

**Comment by marcjwilliams1** [comment]
@caravagn The `suggests` in the DESCRIPTION can work like this can't it? 

Then in the load_vcf function you add something like:
``` r
    if (!requireNamespace("vcfR", quietly = TRUE)) {
      stop("Package \"vcfR\" needed for this function to work. Please install it.",
           call. = FALSE)
    }
```

**Comment by marcjwilliams1** [comment]
Ah yes, this is what @luca-dex link says too...

**Comment by caravagn** [comment]
Fantastic guys; are now master an development in synhc? I am using development locally ...

**Comment by luca-dex** [comment]
If the change is fine to you, we can approve the PR. It goes on development
only. To push it to master we should what that you finish your work on
development

**Comment by caravagn** [comment]
Yes please approve the PR and then push the current development as the new master.

G

**Comment by luca-dex** [comment]
Already fixed
