### ISSUE TITLE
Missing required dependencies

### ISSUE THREAD

**Issue by caravagn** [caravagnalab/mobster#31]
It seems it is currently missing the following CRAN package 

wesanderson
reshape2

plus my github package

ctree

Can we add these to the package so they get downloaded automatically? Should we do that into development and mirror the change to master as well?

**Comment by luca-dex** [comment]
I don't see any reference to a package called `wesanderson`. Both `ctree` and `reshape2` are already present in the version of mobster available on development. 

At the moment `ctree` is only suggested. I'll move it to the depends sections so that is installed as dependency.
