### ISSUE TITLE
Walk-through Example?

### ISSUE THREAD

**Issue by brucemoran** [caravagnalab/mobster#32]
Hi,

I would like to try MOBSTER, but can't see any examples of how to input data, formatting, or what output will look like.

Is there a 'walk-through' with some example data that I can follow?

Thanks,

Bruce.

**Comment by luca-dex** [comment]
Hi @brucemoran,
Have you checked the github.io? https://caravagn.github.io/mobster/

**Comment by brucemoran** [comment]
Hi @luca-dex, 

thanks for getting back to me.

Yes, I've read through the available resources which are very nice.

I should have been more specific in my question, apologies: it is not obvious how to input data for _multiple_ samples.

The general approach per sample I have used is below.

Therefore do I run this across all samples individually to `fit`, then interpret results from multiple output?

I would like to compare (sub)clones between multiple samples from a single patient.

Thanks,

Bruce
```
ds <- read_tsv("data/in/correct/format.tsv")
ds_f <- dplyr::filter(.data = ds, VAF > 0)
m_fit <- mobster_fit(ds_f)
cm_best <- Clusters(m_fit$best)

##ctrees requires driver annotation (arbitrary)
drivers_rows <- c(1, 2, 3)
cm_best$is_driver <- FALSE
cm_best$driver_label <- NA
cm_best$is_driver[drivers_rows] <- TRUE
cm_best$driver_label[drivers_rows] <- c("DR1", "DR2", "DR3")

##fit again
b_fit <- mobster_fit(cm_best)

##ctrees
m_trees <- get_clone_trees(b_fit$best)
m_top_rank <- m_trees[[1]]

##plot
ggpubr::ggarrange(
  ctree::plot.ctree(m_top_rank),
  ctree::plot_CCF_clusters(m_top_rank),
  ctree::plot_clone_size(m_top_rank),
  nrow = 1,
  ncol = 3)
```

**Comment by caravagn** [comment]
Oh now I see - there is no multivariate mobster analysis (tails can be in principle identified from each biopsy sample independently), bu rather there is a pipeline that 

- performs mobster deconvolution from each one of K samples independently;
- determines tail mutations from all samples (i.e., "Tail" in at least one of the K samples);
- removes tail mutations, and run a multivariate Binomial read-counts analysis on all samples together by using with my other tool (VIBER).

This is what we do for the CRC multi-region case study in the paper - you can have a look at the CRC analysis in this repo

https://github.com/caravagn/mobster_supp_data

PS - VAF >0 is not a reasonable filter; the Pareto density requires a sharp cut, I'd suggest VAF > 5%.

**Comment by caravagn** [comment]
Just to be even more clear, the clone tree construction is to be done AFTER the multivariate analysis (ie., from all clusters found in all biopsies).

**Comment by brucemoran** [comment]
Hi Giulio,

thanks for the reply.

I didn't see that supp_data repo before, very nice.

In the multi-region CRC analysis, you run two functions that are not in namespace of any libraries you `require`:
```
mobster_fits = fit_mobsters(Set7_mutations, Set7_samples)
...
non_tail_mutations = get_nontail_mutations(mutations = Set7_mutations, mobster_fits)
```
Therefore how do I find non-tail per sample? 

Data in that repo is combined from the start, I presume I need to make a single dataset of non-tail mutations to `VIBER::variational_fit`(?)

Then from that output, what is input to `ctree::get_clone_trees` (no examples of this in any repos)?

Thanks,

Bruce.

**Comment by caravagn** [comment]
Hi Bruce,

the repo should be attached as SM to the main paper, but is does not matter how you found it. If you see [this](http://htmlpreview.github.io/?https://github.com/caravagn/mobster_supp_data/blob/master/CRC/CRC_vignette.html) you will also see
```
# Source a bunch of auxiliary functions
source('auxiliary_functions.R', verbose = FALSE)
```
which means that the functions are defined [here](https://github.com/caravagn/mobster_supp_data/blob/master/CRC/auxiliary_functions.R).

So if you prepare your data in the exact same format then you can use exactly those ones. I suggest you to run it line by line if you do this analysis for the first time, so you understand exactly what is happing there, and how you get to run VIBER as well.

Cheers

G
