### ISSUE TITLE
Is it possible to deal with ctDNA data?

### ISSUE THREAD

**Issue by ryuji-702** [caravagnalab/mobster#38]
Hi, 
I find the mobster very useful for subclone reconstruction analysis and would like to use it for my ctDNA research.
Could you please let me know if mobster can deal with WES ctDNA data?
Thank you!

**Comment by caravagn** [comment]
Hi @ryuji-702, the tool in principle can process WES data, yes. However, a major point regards the mutational burden you can obtain from WES. If that is low, understanding neutral tails from WES is difficult... Anyway give it a go and try, then look at your fits and decide what is most appropriate.
