### ISSUE TITLE
Model selection failure when sparse low frequency mutations present

### ISSUE THREAD

**Issue by tomouellette** [caravagnalab/mobster#41]
Hi Giulio,

So I've been running lots of examples with mobster (very cool stuff) but I did notice a consistent pattern of model selection failure (weird beta distributions fits) when sparse and dispersed low frequency mutations are present in the VAF. See example plot below (left):

![mobster_failure_example](https://user-images.githubusercontent.com/29900344/128649830-f40e9b4d-17a1-42e7-99a8-bc5c0e97ca84.png)

Both fits were run with the default settings (not auto_setup = FAST).

I think a straight forward solution is to just trim the neutral tail a bit by removing mutations below ~2-5% VAF (see right plot - trimming mutations below 5% VAF fixes this issue), but I am wondering if there is any automated solution within the package for this? Maybe I looked over something in the documentation.

**Comment by caravagn** [comment]
Hi @tomouellette. I usually perform some pre-processing, like removing mutations with VAF < 5%. There is also a mathematical reason to it, which is implied by the tail power law definition. The fit on the right suffers from the lack of a clear clonal peak. May I ask what data are these and what sample purity are you using here?

**Comment by caravagn** [comment]
Any heads up @tomouellette?
