### ISSUE TITLE
No Function: squareplot

### ISSUE THREAD

**Issue by moshl** [caravagnalab/mobster#42]
Hi, I carefully check the funtion in Mobster, but don't see  any information about "squareplot".  Look forward to your update.

Bestwishes,

Sunny.

**Comment by caravagn** [comment]
I apologise but I do not understand what you are referring to @moshl.

Whag is `squareplot`? Where did that come out for you?

I have to post here some code if you seek help.

**Comment by moshl** [comment]
Sorry, I should say more clear.   I download the supplementary data (Caravagna_et_al_2020_Supplementary_Data) from your paper, Subclonal reconstruction of tumors by using machine learning and population genetics, "squareplot" used in the CRC_vignette (html are not support for upload, so i take a screenshot ) as the below :
![image](https://user-images.githubusercontent.com/29252072/141722913-8a560ba8-4729-4288-b7f9-b00c6f130b16.png)
 
Thanks.


> I apologise but I do not understand what you are referring to @moshl.
> 
> Whag is `squareplot`? Where did that come out for you?
> 
> I have to post here some code if you seek help.

**Comment by caravagn** [comment]
The `squareplot` function is defined in the [https://github.com/caravagn/mobster_supp_data/blob/master/CRC/auxiliary_functions.R](auxiliary_functions.R).

Please refer to that.

**Comment by moshl** [comment]
So great! Thank you very much. I found it

**Comment by caravagn** [comment]
Good, I'll close this.
