### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by pawelqs** [caravagnalab/mobster#45]
Hi,

This line in `selection2clonenested()` throws an error that `time` variable is missing. Is it a typo, and should it be the `time1`?
https://github.com/caravagnalab/mobster/blob/b824fe0d44cfb9816e086f3d1c3b6ae39766523a/R/evodynamics.R#L149

Best regards,
Paweł

**Comment by caravagn** [comment]
Hello @pawelqs, just bringing in the loop @marcjwilliams1 which developed that piece of code, and @Militeee as well to double check.

**Comment by Militeee** [comment]
Yea it does look like a typo (as x3 is also defined in the version with one subclone but with time1 instead of time). Can I fix it @caravagn @marcjwilliams1 ?

**Comment by caravagn** [comment]
Fine by me.
