### ISSUE TITLE
Missing line in DESCRIPTION file

### ISSUE THREAD

**Issue by MadeleineDale** [caravagnalab/mobster#46]
Error in `(function (command = NULL, args = character(), error_on_status = TRUE, …`:
! System command 'R' failed
---
Exit status: 1
stdout & stderr: <printed>
---
Type .Last.error to see the more details.
Warning messages:
1: In readLines(f, n) :
  incomplete final line found on '/Users/madeleine.dale/Library/R/arm64/4.3/library/mobster/DESCRIPTION'
2: In readLines(file) :
  incomplete final line found on '/Users/madeleine.dale/Library/R/arm64/4.3/library/mobster/DESCRIPTION'
3: In readLines(f, n) :
  incomplete final line found on '/Users/madeleine.dale/Library/R/arm64/4.3/library/mobster/DESCRIPTION'
4: In readLines(file) :
  incomplete final line found on '/Users/madeleine.dale/Library/R/arm64/4.3/library/mobster/DESCRIPTION'

**Comment by caravagn** [comment]
See #47
