### ISSUE TITLE
Error in vignette during binomial_noise branch build

### ISSUE THREAD

**Issue by MadeleineDale** [caravagnalab/mobster#47]
Error when building binomial_noise branch from repo on Rstudio

   Quitting from lines 31-35 [unnamed-chunk-3] (a4_popgen.Rmd)
   Error: processing vignette 'a4_popgen.Rmd' failed with diagnostics:
   Bad MOBSTER input (list of fits).
   --- failed re-building ‘a4_popgen.Rmd’

Can be worked around by setting 'vignettes = F' in build()

**Comment by caravagn** [comment]
Hi @MadeleineDale, that branch is still under development and vignettes are prepared for `main` only. Vignettes will have to be updated once we do a PR to turn that branch into the new main, which is not going to happen necessarily soon. In general, do disable vignettes as they won't work until refactored as you suggest -- also the manual is inconsistent.

Right now, on that branch, your only help is @Militeee.  

I will leave the issue open to keep the memory on this though.
