### ISSUE TITLE
How to obtain CCF from VAF

### ISSUE THREAD

**Issue by xiw588** [caravagnalab/mobster#48]
Hi, I wonder how to obtain CCF from VAF

Thanks a lot

**Comment by xiw588** [comment]
I think I have figured it out! Having another related question regarding driver gene to plot the clonal trees. So the labelling of driver genes are fully up to the user and do you have any recommended reference for defining driver genes? Thanks

**Comment by caravagn** [comment]
Hi @xiw588 -- driver detection is a complex task. There are many tools you could use, but the simplest option is to get lists of known genes for the cancer you are studying, and then rank your variants by impact.
